version: '3'

services:
 nginx_1:
  image: nginx
  ports:
    - 83:80
  volumes:
    - ./nginx1:/usr/share/nginx/html
    - ./default.conf:/etc/nginx/conf.d/default.conf
 nginx_2:
  image: nginx
  volumes:
    - ./nginx2:/usr/share/nginx/html/nginx2